name: SPFx CICD with O365 CLI

on: [push]

# Set the name of the sppkg file
env:
  sppkgFileName: ${{ 'spfx-cicd.sppkg' }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v1
      
    # Setup node.js runtime
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    # npm install
    - name: Run npm install
      run: npm install
    
    # gulp bundle and package solution
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship    
    
    # Compose the package path and save it in a variable
    - name: Get package path
      run: echo ::set-output name=packagepath::sharepoint/solution/$sppkgFileName
      id: getpackagepath
    
    # Upload artifacts (sppkg file)
    - name: Upload artifact (sppkg file)
      uses: actions/upload-artifact@v1.0.0
      with:
        name: output
        path: ${{ steps.getpackagepath.outputs.packagepath }}
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    # Setup node.js runtime
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    # npm install o365 cli
    - name: Run npm install O365 CLI
      run: npm install -g @pnp/office365-cli
    
    # Download package (sppkg file)
    - name: Download pacakge (sppkg file)
      uses: actions/download-artifact@v1
      with:
        name: output
    
    # Compose the artifact path and store it in a variable
    - name: Get artifact path
      run: echo ::set-output name=artifactpath::output/$sppkgFileName
      id: getartifactpath
    
    # Using o365 cli login to tenant, add app and deploy
    - name: Login to tenant, add app and deploy
      run: |
        o365 login --authType password --userName ${{ secrets.adminUsername }} --password ${{ secrets.adminPassword }}
        o365 spo app add -p ${{ steps.getartifactpath.outputs.artifactpath }} --overwrite
        o365 spo app deploy --name $(basename steps.getartifactpath.outputs.artifactpath)
